### ISSUE TITLE
Migrate to Github

### ISSUE THREAD

**Issue by eneroth** [fluent-development/fluent-development.github.io#15]
- [x] Set up team on Github
- [x] Mirror repo to Github
- [x] Set up Zenhub (or alternative)

- [x] Set up CircleCI
- [x] Upload docker image from GitLab to GitHub registry 
- [x] Build on push to master

**Comment by avocade** [comment]
We can still push master to GitLab until we have CircleCI up and running 👍 So less stress.

**Comment by avocade** [comment]
@eneroth ping here if you have progress on replicating the GitLab CI.

**Comment by avocade** [comment]
Closing.
